development:
  adapter: sqlite3
  database: sinatra_shows_to_watch_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: sinatra_shows_to_watch_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: sinatra_shows_to_watch_production
  pool: 5
  timeout: 5000